---
version: "3.9"

services:
  vault:
    image: hashicorp/vault-enterprise:latest
    container_name: vault
    cap_add:
      - IPC_LOCK
    command: server
    volumes:
      - ~/.aws/config:/home/vault/.aws/config
      - ~/.aws/credentials:/home/vault/.aws/credentials
      - ./docker/vault/data:/vault/file
      - ./docker/vault/logs:/vault/logs
      - ./docker/vault/config:/vault/config
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_TOKEN=root
      - VAULT_LICENSE=$VAULT_LICENSE
      - VAULT_RAFT_NODE_ID=node0
      - VAULT_API_ADDR=http://vault:8200
      - VAULT_CLUSTER_ADDR=http://vault:8201
    ports:
      - 8200:8200
      - 8201:8201
    networks:
      - vault

networks:
  vault:
